airflow:
  service:
    type: ClusterIP
  webReplicas: 1
  config:
    AIRFLOW__CORE__LOGGING_LEVEL: DEBUG
    AIRFLOW__CORE__LOAD_EXAMPLES: True

workers:
  replicas: 1

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

webserver:
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: admin-mike
    email: miguel.moreno@wizeline.com
    firstName: admin mike
    lastName: moreno
    password: adminmike
